title-bold: N.E.W. Musique
title-normal:
email: infonewmusique@gmail.com
description: Magasin de musique situé à la plaza 2 d’Alma. Venez nous voir et profitez de plusieurs services. Réparation, ajustement d’instrument, achat neuf ou usagé. Commandes spéciales disponibles!
baseurl: ""
url: "https://newmusique.com"
author:
street_address: 585 rue Collard O (Plaza 2)
city: Alma
state: Québec
zip_code: G8B 6S9
country: Canada
phone: 1 (418) 480-2727

# Plugins
plugins:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-feed
- jemoji

# Homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url: https://www.facebook.com/NEW-Musique-133325803356003/
github_url: https://github.com/newmusique/newmusique.com

# Build settings
markdown: kramdown

# Plugin: jekyll-seo-tag
twitter:
  username:
google_site_verification:
google_analytics_id: UA-26262500-1
facebook:
  app_id: 757708377907669
  default_image: /assets/images/open-graph-default-image.png

product_categories:
- title: En vente chez N.E.W. Musique
  logos:
  - title: Alesis
    image: Alesis.png
    url: https://www.alesis.com/
  - title: Alto-Professional-logo
    image: Alto-Professional-logo.png
    url: https://www.altoproaudio.com/
  - title: Anolis
    image: anolis.png
    url: https://www.anolislighting.com/
  - title: Ashdownmusic
    image: ashdownmusic.png
    url: https://ashdownmusic.com/
  - title: Beavercreek Guitars
    image: Beavercreek-Guitars.png
    url: http://www.beavercreekguitars.com/
  - title: Blackstar Aplification
    image: Blackstar-Aplification-logo.png
    url: https://www.blackstaramps.com/uk
  # new row
  - title: Danelectro
    image: Danelectro-logo.png
    url: http://danelectro.com/
  - title: dbtechnologies
    image: dbtechnologies.png
    url: http://www.dbtechnologies.com/en/home/
  - title: DDrum
    image: ddrum.png
    url: https://www.ddrum.com/index.php
  - title: Dean Guitars
    image: Dean-Guitars-logo.png
    url: https://www.deanguitars.com/
  - title: Dime Amp
    image: Dime-Amp-Logo.png
    url: https://www.armadilloent.com/dimeamps.html
  - title: DJ Tech
    image: DJ-Tech-logo.png
    url: http://www.djtechpro.com/eng/
  # new row
  - title: dw drums
    image: dw-drums.png
    url: http://www.dwdrums.com/
  - title: Egnater custom amplification
    image: Egnater-custom-amplification-logo.png
    url: http://www.egnateramps.com/
  - title: Elation Professional
    image: Elation-Professional.png
    url: https://www.elationlighting.com/?SID=b7t8f51fu3audtaoh0p1ppjbe0
  - title: FBT audio
    image: FBT-audio-logo.png
    url: http://www.fbtaudio.co.uk/
  - title: Fleabass signature
    image: fleabass.png
    url: https://www.fender.com/pages/flea-signature-bass/
  - title: Gemini Pro Audio
    image: Gemini_ProAudio.png
    url: http://geminisound.com/
  # new row
  - title: Gigskinz
    image: gigskinz-logo-transparent.png
    url: https://web.archive.org/web/20161020111255/http://www.gigskinz.com/
  - title: Hartke Amp
    image: Hartke_Amp.png
    url: http://www.samsontech.com/hartke/
  - title: Jamstands
    image: jamstands.png
    url: http://www.ultimatesupport.com/products/jamstands.html
  - title: Jetcityamplification
    image: jetcityamplification.png
    url: https://www.jetcityamplification.com/
  - title: Konig And Meyer
    image: konig-and-meyer.png
    url: https://www.k-m.de/en
  - title: KrankAmp
    image: KrankAmp.png
    url: http://www.krankamps.com/
  # new row
  - title: Levy's Leathers - Guitar Straps & Bags
    image: LEVY.s-Logo.png
    url: http://www.levysleathers.com/
  - title: Line6
    image: line6-amp-logo.png
    url: https://line6.com/amps/
  - title: Luna Guitars
    image: Luna-Guitars.png
    url: https://www.lunaguitars.com/
  - title: Native Instrument
    image: NativeInstrument.png
    url: https://www.native-instruments.com/en/
  - title: Numark
    image: Numark.png
    url: https://www.numark.com/product_category/controllers
  - title: On Stage Stands
    image: On-Stage-Stands.png
    url: https://on-stage.com/
  # new row
  - title: Orion Symbals
    image: orion.png
    url: http://orioncymbals.com.br/
  - title: Paiste
    image: paiste.png
    url: http://www.paiste.com/
  - title: Promark Drumsticks
    image: Promark-logo.png
    url: http://www.promark.com/
  - title: RoadReadyCases
    image: roadreadycases.png
    url: http://www.roadreadycases.com/
  - title: Rocktron
    image: Rocktron.png
    url: http://www.rocktron.com/
  - title: Sabian
    image: Sabian.png
    url: https://www.sabian.com/en/home
  # new row
  - title: Schecter Guitar Research
    image: Schecter-Guitar-Research-logo.png
    url: http://www.schecterguitars.com/
  - title: Shaw Direct
    image: shawdirect-logo.png
    url: https://www.shawdirect.ca/english/
  - title: Shure
    image: Shure_Logo.png
    url: http://www.shure.com/
  - title: Sicmats
    image: Sicmats.png
    url: https://web.archive.org/web/20130822230404/http://www.sicmats.com/
  - title: Stagg Universe of Music
    image: Stagg-Universe-of-Music-logo-copy.png
    url: https://www.staggmusic.com/
  - title: Studio Master
    image: StudioMaster-logo.png
    url: https://www.studiomaster.com/
  # new row
  - title: Tanglewood Guitars
    image: tanglewood.png
    url: http://www.tanglewoodguitars.co.uk/
  - title: Traxon
    image: Traxon.png
    url: http://www.traxontechnologies.com/
  - title: Vic Firth
    image: Vic-Firth-logo.png
    url: http://vicfirth.com/
  - title: Warwick basses amps
    image: Warwick-basses-amps-logo.png
    url: http://www.warwickbass.com/en/Home.html
  - title: Wharefedale Pro
    image: Wharefedale-Pro-logo.png
    url: http://wharfedalepro.com/
  - title: Zildjian
    image: Zildjian.png
    url: https://zildjian.com/
  # new row
  - title: ZT Amplifiers
    image: zt_amp.png
    url: https://www.ztamplifiers.com/
  - title: skip
  - title: skip
  - title: skip
  - title: skip
  - title: skip